---

#TODO: module cannot find subscription
- name: Create Activation Keys
  katello_activation_key:
    username: "{{ configure_katello_username }}"
    password: "{{ configure_katello_password }}"
    server_url: "{{ configure_katello_server_url }}"
    verify_ssl: "{{ configure_katello_verify_ssl }}"
    name: "{{ item.1.name }}"
    organization: "{{ item.0.name }}"
    lifecycle_environment: "{{ item.1.lifecycle_environment }}"
    content_view: "{{ item.1.content_view }}"
    subscriptions: "{{ item.1.subscriptions }}"
    auto_attach: "{{ item.1.auto_attach | default(omit) }}"
  with_subelements:
    - "{{ configure_katello_organizations }}"
    - activation_keys
  loop_control:
    label: "{{ item.1.name }}"
  tags: [always,ak]
  ignore_errors: yes
