---
- name: build sync plan products
  set_fact:
    sync_plan_products: "{{ sync_plan_products }} + [ '{{ item.0.product }}' ]"
  loop: "{{ lookup('vars', product_item + '_product')|product(satellite_orgs)|list }}" 
  loop_control:
    label: "{{ item.0.product }}"
  register: enable_repo_results
  tags: [katello,sync_plans]

- name: remove duplicate products from sync plan list
  set_fact:
    sync_plan_products: "{{ sync_plan_products | unique }}"
  tags: [katello,sync_plans]

- name: include the product_repos tasks
  include_tasks: product_repos.yml
  vars:
    product_org: "{{ item.1.name }}"
    product_label: "{{ item.0.label }}"
    product_reposets: "{{ item.0.repositories }}"
    product_state: "{{ item.0.state }}"
  loop: "{{ lookup('vars', product_item + '_product')|product(satellite_orgs)|list }}" 
  loop_control:
    label: "{{ item.0.label }}"
  notify: setup syncplan
  tags: [katello,repo]

- name: create/update Content Views
  katello_content_view:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    name: "{{ item.0.name }}"
    organization: "{{ item.1.name }}"
    repositories: "{{ item.0.repos | default(omit) }}"
    state: "{{ item.0.state | default(omit) }}"
  loop: "{{ lookup('vars', product_item + '_cv')|product(satellite_orgs)|list }}" 
  loop_control:
    label: "{{ item.1.name }}"
  tags: [katello,cv]

- name: publish content view to library
  katello_content_view_version:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    content_view: "{{ item.0.name }}"
    organization: "{{ item.1.name }}"
    version: "{{ cv_default_ver }}"
    lifecycle_environments:
      - "{{ cv_default_lc }}"
  loop: "{{ lookup('vars', product_item + '_cv')|product(satellite_orgs)|list }}" 
  loop_control:
    label: "{{ item.0.name }}"
  tags: [katello,cv]

- name: "ensure version one of the content view is in all specified lifecyle environments"
  katello_content_view_version:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    content_view: "{{ item.0.name }}"
    organization: "{{ item.1.name }}"
    version: "{{ cv_default_ver }}"
    lifecycle_environments: "{{ item.1.lifecycle_environments }}"
  loop: "{{ lookup('vars', product_item + '_cv')|product(satellite_orgs)|list }}" 
  loop_control:
    label: "{{ item.0.name }}"
  tags: [katello,cv]

- name: create/update Activation Keys
  katello_activation_key:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    name: "{{ item.0.name }}"
    organization: "{{ item.1.name }}"
    lifecycle_environment: "{{ item.0.lifecycle_environment }}"
    content_view: "{{ item.0.content_view }}"
    subscriptions: "{{ item.0.subscriptions }}"
    auto_attach: "{{ item.0.auto_attach | default(omit) }}"
  loop: "{{ lookup('vars', product_item + '_ak')|product(satellite_orgs)|list }}" 
  loop_control:
    label: "{{ item.0.name }}"
  when: item.0.create
  tags: [katello,ak]

- meta: flush handlers
