---
- name: create/update lifecycle environments
  katello_lifecycle_environment:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    description: "{{ item.desc | default('') }}"
    label: "{{ item.name }}"
    name: "{{ item.name }}"
    organization: "{{ item.org }}"
    prior: "{{ item.prior }}"
    state: "{{ item.state | default(omit) }}"
  with_items: "{{ lifecycle_environments }}"
  loop_control:
    label: "{{ item.name }}"
  when: lifecycle_environments is defined
  tags: [katello,lcenv]

- name: create/update Content Views
  katello_content_view:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    name: "{{ item.1.name }}"
    organization: "{{ item.0.name }}"
    repositories: "{{ item.1.repos | default(omit) }}"
    state: "{{ item.1.state | default(omit) }}"
  with_subelements:
    - "{{ satellite_orgs }}"
    - content_views
  loop_control:
    label: "{{ item.1.name }}"
  register: created_content_view
  tags: [cv]


# TODO: this module appears to be broken, need to create an issue
#- name: publish recently changed content view
#  katello_content_view_version:
#    username: "{{ satellite_admin_user }}"
#    password: "{{ satellite_user_pass }}"
#    server_url: "{{ satellite_url }}"
#    content_view: "{{ item.1.name }}"
#    organizaiton: "{{ item.0.name }}"
#    current_lifecycle_environment: Library
#  with_subelements:
#    - "{{ satellite_orgs }}"
#    - content_views
#  loop_control:
#    label: "{{ item.1.name }}"
#  when: created_content_view.changed

# TODO: refactor and test the below code
#- name: create/update Content View Filters
#  katello_content_view_filter:
#    username: "{{ satellite_admin_user }}"
#    password: "{{ satellite_user_pass }}"
#    server_url: "{{ satellite_url }}"
#    verify_ssl: "{{ configure_ka                          tello_verify_ssl }}"
#    content_view: "{{ item.content_view }}"
#    filter_type: "{{ item.filter_type }}"
#    organization: "{{ item.organization }}"
#    date_type: "{{ item.date_type | default(omit) }}"
#    end_date: "{{ item.end_date | default(omit) }}"
#    errata_id: "{{ item.errata_id | default(omit) }}"
#    inclusion: "{{ item.inclusion | default(omit) }}"
#    max_version: "{{ item.max_version | default(omit) }}"
#    min_version: "{{ item.min_version | default(omit) }}"
#    repositories: "{{ item.repositories | default(omit) }}"
#    rule_name: "{{ item.rule_name | default(omit) }}"
#    start_date: "{{ item.start_date | default(omit) }}"
#    types: "{{ item.types | default(omit) }}"
#    version: "{{ item. version| default(omit) }}"
#    filter_state: "{{ item.filter_state | default(omit) }}"
#    rule_state: "{{ item.rule_state | default(omit) }}"
#  with_items: "{{ configure_katello_content_view_filters }}"
#  when: configure_katello_content_view_filters is defined
#
#- name: create/update Content View Versions
#  katello_content_view_version:
#    username: "{{ satellite_admin_user }}"
#    password: "{{ satellite_user_pass }}"
#    server_url: "{{ satellite_url }}"
#    verify_ssl: "{{ satellite_verify_ssl }}"
#    content_view: "{{ item.content_view }}"
#    organization: "{{ item.organization }}"
#    current_lifecycle_environment: "{{ item.current_lifecycle_environment | default#(omit) }}"
#    force_promote: "{{ item.current_lifecycle_environment | default(omit) }}"
#    force_yum_metadata_regeneration: "{{ item.force_yum_metadata_regeneration | #default(omit) }}"
#    lifecycle_environments: "{{ item.lifecycle_environments | default(omit) }}"
#    synchronous: "{{ item.synchronous | default(omit) }}"
#    version: "{{ item.version | default(omit) }}"
#    state: "{{ item.state | default(omit) }}"
#  with_items: "{{ configure_katello_content_view_versions }}"
#  when: configure_katello_content_view_versions is defined
#

#TODO: module cannot find subscription
- name: create/update Activation Keys
  katello_activation_key:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    name: "{{ item.1.name }}"
    organization: "{{ item.0.name }}"
    lifecycle_environment: "{{ item.1.lifecycle_environment }}"
    content_view: "{{ item.1.content_view }}"
    subscriptions: "{{ item.1.subscriptions }}"
    auto_attach: "{{ item.1.auto_attach | default(omit) }}"
  with_subelements:
    - "{{ satellite_orgs }}"
    - activation_keys
  loop_control:
    label: "{{ item.1.name }}"
  tags: [ak]
  ignore_errors: yes

