---
- name: getting organizaitons for lifecycle environments
  include_tasks: lifecyle_env.yml
  loop: "{{ satellite_orgs }}"
  loop_control:
    loop_var: outer_item
    label: outer_item.name
  tags: [katello,lcenv]

# This will enable rh product repos and create the content views
- name: get products to enable
  include_tasks: products.yml
  loop: "{{ satellite_orgs|subelements('products') }}"
  loop_control:
    loop_var: orgs
    label: "{{ orgs.1 }}_product"
  tags: [katello,ak,products,cv,promote]
