---
- name: Create Domains
  foreman_domain:
    username: "{{ configure_katello_username }}"
    password: "{{ configure_katello_password }}"
    server_url: "{{ configure_katello_server_url }}"
    verify_ssl: "{{ configure_katello_verify_ssl }}"
    name: "{{ item.name }}"
    organizations: "{{ item.orgs | default(omit) }}"
    locations: "{{ item.locations | default(omit) }}"
    dns_proxy: "{{ item.proxy | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    description: "{{ item.desc | default(omit) }}"
  with_items: "{{ domains }}"
  loop_control:
    label: "{{ item.name }}"
  when: domains is defined
