---
- name: Enable EPEL
  yum_repository:
    name: epel
    state: present
    description: EPEL Yum repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    proxy: "{{ configure_katello_proxy | default(omit) }}"
    proxy_password: "{{ configure_katello_proxy_password | default(omit) }}"
    proxy_username: "{{ configure_katello_proxy_username | default(omit) }}"

- name: Install pip
  package:
    name: python-pip
    state: present

- name: Install nailgun
  pip:
    name: nailgun
