---
- name: Install epel
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install pip
  package:
    name: python-pip
    state: present

- name: Install nailgun
  pip:
    name: https://github.com/SatelliteQE/nailgun/tarball/6.2.z

- name: Install python-foreman
  pip:
    name: git+https://github.com/Nosmoht/python-foreman.git#master 
