---
- name: Enable EPEL
  yum_repository:
    name: epel
    state: present
    enabled: no
    description: EPEL Yum repo
    baseurl: https://dl.fedoraproject.org/pub/epel/$releasever/$basearch/
    proxy: "{{ configure_katello_proxy_url | default(omit) }}"
    proxy_username: "{{ configure_katello_proxy_username | default(omit) }}"
    proxy_password: "{{ configure_katello_proxy_password | default(omit) }}"
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
  when: pip_repo_epel

- name: Install pip
  package:
    name: python-pip
    enablerepo: epel
    state: present
  when: pip_repo_epel

- name: install python-pip
  yum:
    name: python-pip
    enablerepo: "rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms"
    state: present
  when: not pip_repo_epel

- name: Enable python scl_source
  shell: >
    source scl_source enable {{ var_py_version }}
  when: not pip_repo_epel

- name: Export {{ var_py_version }} environment
  shell: >
    export LD_LIBRARY_PATH=/opt/rh/{{ var_py_version }}/root/usr/lib64
  when: not pip_repo_epel

- name: Export {{ var_py_version }} environment
  shell: >
    export LD_LIBRARY_PATH=/opt/rh/{{ var_py_version }}/root/usr/lib64
  when: not pip_repo_epel

- name: Build extra arguments when configure_katello_proxy is defined
  set_fact:
    build_extra_args: "{{ '--proxy ' + (configure_katello_proxy | urlsplit('scheme')) + '://' + configure_katello_proxy_username + ':' + configure_katello_proxy_password + '@' + (configure_katello_proxy | urlsplit('hostname')) + ':' + (configure_katello_proxy | urlsplit('port') | string) }}"
  when: configure_katello_proxy

- name: Install nailgun
  pip:
    name: "{{ configure_katello_nailgun_package }}"
    version: "{{ configure_katello_nailgun_version | default(omit) }}"
    virtualenv: "{{ configure_katello_nailgun_virtualenv | default(omit) }}"
    extra_args: "{{ build_extra_args | default(omit) }}"