---
- import_tasks: install.yml
  when: configure_katello_install_deps
  tags:
    - install

- import_tasks: settings.yml
  tags:
    -  settings

- import_tasks: taxonomies.yml
  tags:
    - taxonomies
    - tax
    - org

- import_tasks: manifest.yml
  tags:
    - manifest

- import_tasks: repositories.yml
  tags:
    - repos
    - repositories
    - repository

- import_tasks: sync_plans.yml
  tags:
    - sync_plans

- import_tasks: lifecycle_environments.yml
  tags:
    - lifecycle_environments
    - lenv
    - lenvs

- import_tasks: content_views.yml
  tags:
    - content_views
    - content_view
    - cvs
    - cv

- import_tasks: content_view_versions.yml
  tags:
    - content_view_versions
    - content_view_version
    - cvvs
    - cvv

- import_tasks: activation_keys.yml
  tags:
    - activation_keys
    - activation_key
    - aks
    - ak
