---
- name: include satellite content views variables
  include_vars: "../vars/satellite_content_views.yml"
  tags: [always]

- name: include satellite products variables
  include_vars: "../vars/satellite_products.yml"
  tags: [always]

- name: include satellite activation keys
  include_vars: "../defaults/activation_keys.yml"
  tags: [always]

- name: setup epel repo, install python-pip and install nailgun pip
  import_tasks: "{{ role_path }}/tasks/install.yml"
  when: configure_katello_nailgun_install
  tags: [nailgun]

- name: create orgs and locations
  import_tasks: "{{ role_path }}/tasks/taxonomies.yml"
  tags: [katello,org,location,taxonomies]

- name: setup manifest
  import_tasks: "{{ role_path }}/tasks/manifest.yml"
  tags: [katello,manifest]

- name: enable red hat products repos and repositories
  import_tasks: "{{ role_path }}/tasks/products.yml"
  tags: [katello,repos,products,sync_plans]

- name: create/update satellite content
  import_tasks: "{{ role_path }}/tasks/content.yml"
  tags: [katello,cv,lcenv]

- name: create/update domains
  import_tasks: "{{ role_path }}/tasks/provision.yml"
  tags: [provision,domains,subnets,compute]

#*******************************************#
# ABOVE THIS LINE WORKS                     #
#############################################

#- import_tasks: "{{ role_path }}/tasks/settings.yml"
#  tags:
#    -  settings
#    - repository

