---
- name: include satellite content views variables
  include_vars: "../vars/satellite_content_views.yml"

- name: include satellite content views variables
  include_vars: "../vars/satellite_content_views.yml"

- name: include satellite products variables
  include_vars: "../vars/satellite_products.yml"

# Create orgs and locations
#- import_tasks: "{{ role_path }}/tasks/taxonomies.yml"
#  tags: [org,location,taxonomies]

#- import_tasks: "{{ role_path }}/tasks/manifest.yml"
#  tags:
#    - manifest

#- import_tasks: "{{ role_path }}/tasks/redhat_products.yml"
#  tags:
#    - repos
#    - repositories

#- import_tasks: "{{ role_path }}/tasks/sync_plans.yml"
#  tags:
#    - sync_plans

# - import_tasks: "{{ role_path }}/tasks/content_views.yml"
#   tags:
#     - content_views
#     - content_view
#     - cvs
#     - cv

#- import_tasks: "{{ role_path }}/tasks/activation_keys.yml"
#  tags:
#    - activation_keys
#    - activation_key
#    - aks
#    - ak

#*******************************************#
# ABOVE THIS LINE WORKS                     #
#############################################

#- import_tasks: "{{ role_path }}/tasks/settings.yml"
#  tags:
#    -  settings
#    - repository


#- import_tasks: "{{ role_path }}/tasks/lifecycle_environments.yml"
#  tags:
#    - lifecycle_environments
#    - lenv
#    - lenvs


# - import_tasks: "{{ role_path }}/tasks/domains.yml"
#   tags:
#     - domain
#     - domains
