---
- name: include satellite content views variables
  include_vars: "../vars/satellite_content_views.yml"
  tags: [always]

- name: include satellite content views variables
  include_vars: "../vars/satellite_content_views.yml"
  tags: [always]

- name: include satellite products variables
  include_vars: "../vars/satellite_products.yml"
  tags: [always]

- name: setup epel repo, install python-pip and install nailgun pip
  import_tasks: "{{ role_path }}/tasks/install.yml"
  when: configure_katello_nailgun_install
  tags: [nailgun]

- name: create orgs and locations
  import_tasks: "{{ role_path }}/tasks/taxonomies.yml"
  tags: [katello,org,location,taxonomies]

- name: setup manifest
  import_tasks: "{{ role_path }}/tasks/manifest.yml"
  tags: [katello,manifest]

- name: enable red hat products repos and repositories
  import_tasks: "{{ role_path }}/tasks/redhat_products.yml"
  tags: [katello,repos,products]

- name: create sync plans
  import_tasks: "{{ role_path }}/tasks/sync_plans.yml"
  tags: [katello,sync_plans]

# - import_tasks: "{{ role_path }}/tasks/content_views.yml"
#   tags:
#     - content_views
#     - content_view
#     - cvs
#     - cv

#- import_tasks: "{{ role_path }}/tasks/activation_keys.yml"
#  tags:
#    - activation_keys
#    - activation_key
#    - aks
#    - ak

#*******************************************#
# ABOVE THIS LINE WORKS                     #
#############################################

#- import_tasks: "{{ role_path }}/tasks/settings.yml"
#  tags:
#    -  settings
#    - repository


#- import_tasks: "{{ role_path }}/tasks/lifecycle_environments.yml"
#  tags:
#    - lifecycle_environments
#    - lenv
#    - lenvs


# - import_tasks: "{{ role_path }}/tasks/domains.yml"
#   tags:
#     - domain
#     - domains
