---
- name: manifest | Attach subs
  redhat_manifest:
    name: "{{ manifest_name }}"
    username: "{{ configure_rhsm_username }}"
    password: "{{ configure_rhsm_password }}"
    pool_id: "{{ item.pool_id }}"
    quantity: "{{ item.quantity }}"
    state: "{{ item.state }}"
    validate_certs: "{{ configure_rhsm_verify_ssl }}"
  with_items: "{{ configure_katello_subscriptions }}"
  when:
    - configure_katello_subscriptions is defined
    - not configure_katello_copy_manifest
  register: subs
  environment:
    http_proxy: "{{ (configure_katello_proxy is defined) | ternary( (configure_katello_proxy | urlsplit('scheme')) + '://' + configure_katello_proxy_username + ':' + configure_katello_proxy_password + '@' + (configure_katello_proxy | urlsplit('hostname')) + ':' + (configure_katello_proxy | urlsplit('port') | string), '') }}"
    https_proxy: "{{ (configure_katello_proxy is defined) | ternary( (configure_katello_proxy | urlsplit('scheme')) + '://' + configure_katello_proxy_username + ':' + configure_katello_proxy_password + '@' + (configure_katello_proxy | urlsplit('hostname')) + ':' + (configure_katello_proxy | urlsplit('port') | string), '') }}"

- name: manifest | Download manifest
  redhat_manifest:
    name: "{{ manifest_name }}"
    username: "{{ configure_rhsm_username }}"
    password: "{{ configure_rhsm_password }}"
    validate_certs: "{{ configure_rhsm_verify_ssl }}"
    path: "{{ configure_katello_manifest_path}}/{{ manifest_name }}.zip" 
  when:
    - manifest_name is defined and configure_katello_download_manifest
    - not configure_katello_copy_manifest
  environment:
    http_proxy: "{{ (configure_katello_proxy is defined) | ternary( (configure_katello_proxy | urlsplit('scheme')) + '://' + configure_katello_proxy_username + ':' + configure_katello_proxy_password + '@' + (configure_katello_proxy | urlsplit('hostname')) + ':' + (configure_katello_proxy | urlsplit('port') | string), '') }}"
    https_proxy: "{{ (configure_katello_proxy is defined) | ternary( (configure_katello_proxy | urlsplit('scheme')) + '://' + configure_katello_proxy_username + ':' + configure_katello_proxy_password + '@' + (configure_katello_proxy | urlsplit('hostname')) + ':' + (configure_katello_proxy | urlsplit('port') | string), '') }}"

- name: manifest | Copy manifest
  copy:
    src: "{{ manifest_name }}.zip"
    dest: "{{ configure_katello_manifest_path}}/{{ item.manifest }}"
    mode: 0644
  when:
    - manifest_name is defined
    - configure_katello_copy_manifest
  register: manifest
  with_items: "{{ configure_katello_organizations }}"

- name: "manifest | Upload Katello manifests"
  katello_manifest:
    username: "{{ configure_katello_username }}"
    password: "{{ configure_katello_password }}"
    server_url: "{{ configure_katello_server_url }}"
    verify_ssl: "{{ configure_katello_verify_ssl }}"
    organization: "{{ item.name }}"
    manifest_path: "{{ configure_katello_manifest_path}}/{{ item.manifest }}.zip" 
    redhat_repository_url: "{{ item.redhat_repository_url | default(omit) }}"
    state: present
  with_items: "{{ configure_katello_organizations }}"
  when:
    - subs.changed or manifest.changed or configure_katello_force_manifest_upload
    - configure_katello_organizations is defined
    - item.manifest is defined
    - item.state == "present"
