---
- name: create manifest, attach subs and download from RHSM
  import_tasks: "{{ role_path }}/tasks/rhsm_manifest.yml"

- name: manifest | Copy manifest
  copy:
    src: "{{ configure_katello_manifest_path }}/{{ item.manifest }}.zip"
    dest: "/root/{{ item.manifest }}.zip"
    mode: 0644
  register: manifest
  with_items: "{{ configure_katello_organizations }}"
  loop_control: 
    label: "{{ item.manifest }}"
  when: 
    - configure_katello_copy_manifest
#    - not( (item.manifest is none ) or (item.manifest | trim == '') )
#    - item.state == "present"

- name: "manifest | Upload Katello manifests"
  katello_manifest:
    username: "{{ configure_katello_username }}"
    password: "{{ configure_katello_password }}"
    server_url: "{{ configure_katello_server_url }}"
    verify_ssl: "{{ configure_katello_verify_ssl }}"
    organization: "{{ item.name }}"
    manifest_path: "/root/{{ item.manifest }}.zip"
    redhat_repository_url: "{{ item.manifest_url | default(omit) }}"
    state: present
  with_items: "{{ configure_katello_organizations }}"
  loop_control: 
    label: "{{ item.manifest }}"
  when:
    - manifest.changed or upload_manifest or configure_katello_force_manifest_upload
#    - not( (item.manifest is none ) or (item.manifest | trim == '') )
#    - item.state == "present"
