---
- name: "Enable repository sets"
  katello_repository_set:
    username: "{{ configure_katello_username }}"
    password: "{{ configure_katello_password }}"
    server_url: "{{ configure_katello_server_url }}"
    verify_ssl: "{{ configure_katello_verify_ssl }}"
    name: "{{  item.name }}"
    organization: "{{ item.organization }}"
    product: "{{ item.product }}"
    repositories: "{{ item.repositories }}"
    state: "{{ item.state }}"
  with_items: "{{ configure_katello_repository_sets }}"
  when: configure_katello_repository_sets is defined
  notify:
    - sync all repositories

- name: "Enable Custom repositories"
  katello_repository:
    username: "{{ configure_katello_username }}"
    password: "{{ configure_katello_password }}"
    server_url: "{{ configure_katello_server_url }}"
    verify_ssl: "{{ configure_katello_verify_ssl }}"
    name: "{{  item.name }}"
    organization: "{{ item.organization }}"
    product: "{{ item.product }}"
    state: "{{ item.state | default(omit) }}"
    content_type: "{{ item.content_type }}"
    url: "{{ item.url | default(omit) }}"
    gpg_key: "{{ item.gpg_key | default(omit) }}"
    download_policy: "{{ item.download_policy | default(omit) }}"
  with_items: "{{ configure_katello_repositories }}"
  when: configure_katello_repositories is defined
  notify:
    - sync all repositories

- name: Sync Repositories
  meta: flush_handlers
