---
- name: manifest | Attach subs
  redhat_manifest:
    name: "{{ item.0.manifest }}"
    username: "{{ configure_rhsm_username }}"
    password: "{{ configure_rhsm_password }}"
    pool_id: "{{ item.1.id }}"
    quantity: "{{ item.1.quantity }}"
    state: "{{ item.1.state }}"
    validate_certs: "{{ configure_rhsm_verify_ssl }}"
  with_subelements:
    - "{{ configure_katello_organizations }}"
    - pool
  when:
    - not( (item.1.id is none ) or (item.1.id | trim == '') )
    - configure_katello_create_manifest
  register: subs
  environment:
    http_proxy: "{{ (configure_katello_proxy is defined) | ternary( #configure_katello_proxy | urlsplit('scheme')) + '://' + configure_katello_proxy_username + ':' + configure_katello_proxy_password + '@' #+ configure_katello_proxy | urlsplit('hostname')) + ':' + #(configure_katello_proxy | rlsplit('port') | string), '') }}"
    https_proxy: "{{ (configure_katello_proxy is defined) | ternary( #configure_katello_proxy | urlsplit('scheme')) + '://' + configure_katello_proxy_username + ':' + configure_katello_proxy_password + '@' #+ configure_katello_proxy | urlsplit('hostname')) + ':' + #(configure_katello_proxy | rlsplit('port') | string), '') }}"

- name: manifest | Download manifest
  redhat_manifest:
    name: "{{ item.0.manifest }}"
    username: "{{ configure_rhsm_username }}"
    password: "{{ configure_rhsm_password }}"
    validate_certs: "{{ configure_rhsm_verify_ssl }}"
    path: "{{ configure_katello_manifest_path}}/{{ item.0.manifest }}.zip"
  with_subelements:
    - "{{ configure_katello_organizations }}"
    - pool
  when:
    - item.0.manifest is defined and configure_katello_download_manifest
    - configure_katello_download_manifest
  environment:
    http_proxy: "{{ (configure_katello_proxy is defined) | ternary( ##configure_katello_proxy | urlsplit('scheme')) + '://' + #configure_katello_proxy_username + ':' + configure_katello_proxy_password + '@' ##+ configure_katello_proxy | urlsplit('hostname')) + ':' + ##(configure_katello_proxy | rlsplit('port') | string), '') }}"
    https_proxy: "{{ (configure_katello_proxy is defined) | ternary( ##configure_katello_proxy | urlsplit('scheme')) + '://' + #configure_katello_proxy_username + ':' + configure_katello_proxy_password + '@' ##+ configure_katello_proxy | urlsplit('hostname')) + ':' + ##(configure_katello_proxy | rlsplit('port') | string), '') }}"
