---
- name: Set Settings
  foreman_setting:
    username: "{{ configure_katello_username }}"
    password: "{{ configure_katello_password }}"
    server_url: "{{ configure_katello_server_url }}"
    verify_ssl: "{{ configure_katello_verify_ssl }}"
    name: "{{ item.name }}"
    value: "{{ item.value | default(omit) }}"
  with_items: "{{ configure_katello_settings }}"
  when: configure_katello_settings is defined
  tags:
    -  settings
