---
- name: Create Sync Plans
  katello_sync_plan:
    username: "{{ configure_katello_username }}"
    password: "{{ configure_katello_password }}"
    server_url: "{{ configure_katello_server_url }}"
    verify_ssl: "{{ configure_katello_verify_ssl }}"
    name: "{{ item.name }}"
    organization: "{{ item.organization }}"
    interval: "{{ item.interval }}"
    enabled: "{{ item.enabled }}"
    sync_date: "{{ item.sync_date }}"
    products: "{{ item.products }}"
  with_items: "{{ configure_katello_sync_plans }}"
  when: configure_katello_sync_plans is defined
