---
- name: taxonomies | create Organizations
  foreman_organization:
    username: "{{ configure_katello_username }}"
    password: "{{ configure_katello_password }}"
    server_url: "{{ configure_katello_server_url }}"
    verify_ssl: "{{ configure_katello_verify_ssl }}"
    name: "{{ item.0.name }}"
    state: "{{ item.0.state }}"
  with_subelements:
    - "{{ configure_katello_organizations }}"
    - pool

- name: taxonomies | create locations
  foreman_location:
    username: "{{ configure_katello_username }}"
    password: "{{ configure_katello_password }}"
    server_url: "{{ configure_katello_server_url }}"
    verify_ssl: "{{ configure_katello_verify_ssl }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    organizations: "{{ item.orgs }}"
  with_items: "{{ configure_katello_locations }}"
