---
- name: taxonomies | create Organizations
  foreman_organization:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ satellite_orgs }}"
  loop_control:
    label: "{{ item.name }}"
  tags: [katello,org]

- name: taxonomies | create locations
  foreman_location:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    name: "{{ item.1.name }}"
    state: "{{ item.1.state }}"
    organizations: "{{ item.0.name }}"
  with_subelements:
    - "{{ satellite_orgs }}"
    - location
  loop_control:
    label: "{{ item.1.name }}"
  tags: [katello,location]
